name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Configure GitHub credentials
      run: |
        git config --global user.name "demrebicer"
        git config --global user.email "demrebicer33@gmail.com"

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SECRET_PRIVATE_KEY }}
        
    - name: Run deploy
      run: npm run deploy
